### ISSUE TITLE
`Invalid JSON in options` error when omitting the options input entirely

### ISSUE THREAD

**Issue by SimJoSt** [deployphp/action#77] opened 2024-01-16 16:42 UTC
When calling the deployer GitHub action without setting any values for the `options` input, the following error message appears: `Invalid JSON in options`
It doesn't break the deployment, however an error message in a successful deployment log feels weird :) And with no actual problems occurring, I was wondering if the error detection is slightly off.
I'm not familiar with the try-catch logic yet, so I cannot provide and improvement as a PR at this time.

Relevant code snippet:
https://github.com/deployphp/action/blob/06aeb295d6432970d615c5551e3d941e50349c46/index.js#L116-L126

Readme section:
https://github.com/deployphp/action/blob/06aeb295d6432970d615c5551e3d941e50349c46/README.md?plain=1#L26-L29

## Upvote & Fund

- We're using [Polar.sh](https://polar.sh/deployphp) so you can upvote and help fund this issue.
- We receive the funding once the issue is completed & confirmed by you.
- Thank you in advance for helping prioritize & fund our backlog.

<a href="https://polar.sh/deployphp/action/issues/77">
<picture>
  <source media="(prefers-color-scheme: dark)" srcset="https://polar.sh/api/github/deployphp/action/issues/77/pledge.svg?darkmode=1">
  <img alt="Fund with Polar" src="https://polar.sh/api/github/deployphp/action/issues/77/pledge.svg">
</picture>
</a>

**Comment by Milkman337** [comment] 2024-03-21 09:55
any update on this

**Comment by tobz-nz** [comment] 2024-06-21 04:02
duplicate of #72

**Closed as not planned** 2024-07-29 15:41 UTC
